### ISSUE TITLE
Links on "References" page are sorted case sensitive

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#101]
On this page: https://docs.codewars.com/references/ all uppercase links come before lowercase links, what makes for example `ZUT` appear on the middle page.

**Comment by hobovsky** [comment]
`RSpec` comes before `Rackunit` and `Ranks`. It still seems to be out of order, unless I get alphabetic sorting wrong:

![image](https://user-images.githubusercontent.com/23709795/89030697-47d1a000-d331-11ea-951d-2fbc7484647f.png)

**Comment by kazk** [comment]
That's because it's sorted by the title's slug and camel cased word is split into separate words by default. So `RSpec` is `r-spec` and `RackUnit` is `rack-unit`.
I can change the `slugify` option to `decamelize: false`.
