### ISSUE TITLE
working example or tutorial about creating a sql kata

### ISSUE THREAD

**Issue by opensas** [codewars/docs#104]
I have more than 1500 reputation and already created a couple of Javascript kata

I´d like to create a sql kata, but I have no clue about how to start with

Is there a tutorial or a complete example that I could have a look at?

I can only see the test cases but I don't know how to setup the initial data (create table, inserts, etc) or the expected result.

thanks a lot

**Comment by Blind4Basics** [comment]
@ggorlen : could you provide an example of random tests with this, plz?

**Comment by ggorlen** [comment]
Sure, either [Faker](https://github.com/faker-ruby/faker) or `rand`/`sample` works to generate mock data. Then [run the reference query on the database](https://sequel.jeremyevans.net/rdoc/files/doc/cheat_sheet_rdoc.html#label-Using+raw+SQL) and assert the comparison of the result arrays as normal:

```ruby
# ...
  it "should work on a random test" do
    40.times do
      name = (1..rand(1..4)).map {"foo".chars.sample}.join
      DB[:widgets].insert(name: name)
    end
    
    ref_soln_query = "SELECT * FROM widgets WHERE widgets.name LIKE 'foo%';"
    expected = DB[ref_soln_query].to_a()
    actual = run_sql.to_a()
    show_diff_table(actual, expected)
    expect(actual).to eq(expected)
  end
# ...
```

Happy to hear any improvements/suggestions you might have.

**Comment by Blind4Basics** [comment]
thx! :+1:  (unforunately, I cannot suggest anything since I didn't ever write a sql test site... ;/ )

PR: #105. If wanna take a quick look to it. ;)

cheers & thx again.

**Comment by ggorlen** [comment]
There's a problem with the approach as I originally posted. The way `show_diff_table` and `run_sql` interact causes the table to fail to render when the select statement returns no rows. I've updated the example to handle this case. Hopefully it's the only edge case but we might want to hold off on https://github.com/codewars/docs/issues/104 for a bit until it can be better validated. Luckily, the approach is being exercised in the field so I have reason to believe any issues will surface soon.

**Comment by Blind4Basics** [comment]
thx! I updated the PR.
