### ISSUE TITLE
Import 'About\Kata'

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#117]
Breakdown of #5 .

Move https://github.com/codewars/codewars.com/wiki/Kata section to new docs.

I plan to move all pages in one go, in initial approach do not focus too much on the content, but move files, update markdowns, add navigation, fix errors etc. Content organization issues will probably appear in the process, and then we can think what move where and how to tag it.

Any ideas, as usually, are very welcome.

**Comment by Blind4Basics** [comment]
I'm not really fond of the idea. Importing a lot of things that are sometimes of rather poor quality (not foten, but still) and whose break down might not suit at all what we actually need might be a huge brake and building something in "better shape", more approrpiate to "our" actual need. I mean, building something as a whole, an dnot using patches added ones over the others for years.


No?

**Comment by hobovsky** [comment]
My initial assumption was that since we have what we have on current wiki, we haven;t changed it and we still use it, then it's good enough to have it imported in this form as a first step. But of course I understand what you mean, and I will think about how to approach it in some smarter way.

**Comment by Blind4Basics** [comment]
yeah, sure. We won't rewrite everything from scratch. But it's _the shot_ at rebuilding the overall structure/organization.

**Comment by hobovsky** [comment]
@kazk a question: what should we do about [kata ranking guidelines](content/references/kata_ranking/index.md)? Do they still hold, should we keep them in docs, or just drop docs about it?

**Comment by hobovsky** [comment]
In PR #129 you can see something what would be my proposal of breakdown for concepts related to kata. My idea generally went this way:

 - "Concepts" part would contain some explanations on "What is X" and "How does X work in the system". For example the part on translations would contain some explanations what is a language version, what can be done with it, that they can be published, accepted, details of mechanisms and criteria for approval etc. It would be the "technical"/functional part.
 - "Recipes" part would contain some howtos related so some specific activity: "how to write a good translation", "how to review translation properly" etc. It would contain guidelines, best practices, and such.
 - articles related to one topic in both pats would be linked together somehow, either via sidebar, or with some "See also" page/footnote.
 - Additionally, "Reference" page would be created where applicable, with tables, numbers, figures, and such.

There's no content in the pages yet, only some things imported from old wiki but they would be redacted anyway. I would just want to hear your feedback on the proposed breakdown. Is it OK, or totally the wrong way. If you think it's too early to say I can prepare some content on every topic so we could see how it goes.

**Comment by kazk** [comment]
> @kazk a question: what should we do about kata ranking guidelines? Do they still hold, should we keep them in docs, or just drop docs about it?

I think it's outdated and the examples listed are misleading/unclear. But we should have something.
For now, maybe add a warning at the top acknowledging that it's outdated, and encourage readers to provide feedback?

---

Your proposed breakdown sounds great :+1: We can always adjust later if we find a better way, so don't worry too much and go for it.

**Comment by hobovsky** [comment]
I decided to merge the branch with breakdown, because it now enables me to work on specific parts (translations, beta process, etc).

Currently it contains mostly placeholders or stuff imported from old wiki, but I hope to fill the gaps gradually in a way similar to my description of beta process in #131.

I will request reviews for specific parts, but if you have any remarks on the brakdown itself, then let me know.
