### ISSUE TITLE
add anchors to Term objects in the glossary

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#119]
# Currently

At the moment, these kind of links can be assigned to `Terms` objects:
* external links, through the `links` property
* links internal to codewars.docs, thourgh the `see` property

It's not possible to link terms of the glossary between them

# Expected

Be able to link terms of the glossary to one another, like:

> * Example tests: blablabla
> ...
> * Sample tests:  see [example tests]()

# Suggestion

Add... something... and what's needed with it so that one (or even both) of the following is possible:

* Either: adding the link to the other term inside the description of the `Term.term` property of the target
```markdown
- term: Sample tests
  description: "See [example tests](#Example-tests)."
```

* Or having a link added automatically through a new property like this:
```markdown
- term: Sample tests
  description: ""
  anchoredTo: "Example tests"
```

or possibly, to avoid to have to update that new property if a `term` is changed:

```markdown
- term: Example tests
  description: ...
  anchor: ThisWouldBeAnAnchor

...

- term: Sample tests
  description: ""
  anchoredTo: ThisWouldBeAnAnchor
```
And that would automatically add the link below the term in the glossary, linke the `links` or `see` properties.

the `anchor` property could be by default a "slugification" of the `term` propoerty as long as it's not defined.
Both would be optionnal.

**Comment by kazk** [comment]
Isn't it already done? Each `<div>` containing the term have `id` set to slugified term.

https://docs.codewars.com/glossary/#example-tests

But it looks like it's partially covered by the header so I need to fix that like I did with the Markdown pages.

**Comment by Blind4Basics** [comment]
ah good. I didn't think about using that. :+1: 
I'll update the glossary thread about that then I'll close this one.

**Comment by Blind4Basics** [comment]
done :+1:

**Comment by Blind4Basics** [comment]
I've been playing with this this morning and observed the following things:

### `See` doesn't work for an entry of the glossary

```yaml
- term: Sample 
  see: /glossary/#example-tests
```
Nothing happens. I guess it's because the link isn't to a page itself, but a specific nchor in the glossary page.

___Q:___ can this be changed so that internal links in the glossary works the same way they do everywhere else? (meaning: `[...](/glossary/#example-tests)` would work in other pages of the docs)

### Using `links` open a new tab in the browser

It seems weird when linking to another entry of the glossary...


### Enhancement?

I guess that the `see` property will open a new tab to, so here I come again: maybe it could be nice to have:

* either a dedicated property i the `Term` class so that the user isn't sent to the target using another tab
* or a way to customise the existing structure so that the link doesn't open in a new tab when `glossary` is found in the url _and_ the user is currently already in the glossary...?

Any thoughts?

**Comment by kazk** [comment]
@Blind4Basics 

> `see` doesn't work for an entry of the glossary

That's because `see` is a path to a page providing further information.

https://github.com/codewars/docs/blob/735223345e9261c610dcf00541c8af557ac75e99/data/glossary.yml#L16-L17

Link from `see` shouldn't open a new tab. If it does, then that's a bug.

> Q: can this be changed so that internal links in the glossary works the same way they do everywhere else? (meaning: `[...](/glossary/#example-tests)` would work in other pages of the docs)

If `[...](/glossary/#example-tests)` is in `description`, it should work the same way. Can you clarify?

> Using `links` open a new tab in the browser

Yes, because links are for external links as documented in the file.

https://github.com/codewars/docs/blob/735223345e9261c610dcf00541c8af557ac75e99/data/glossary.yml#L18-L19

Can you explain the use case? I don't think I'm understanding the problem. `see` creates a link to a page explaining the term in more detail from a path. `links` are external links containing further information. Link to the other term in `description` using the id should work as expected.

**Comment by Blind4Basics** [comment]
Mmmh ok. I didn't think about the simplest way (the markdown in the description part... :/ ). About see/links, ok, that makes sense. No problem, so. I just need to wrap my mind about the details yet.

:+1: 

---

ok, I just checked:

* `see` is opening in the same tab
*  the link through the description works like a charm.
