### ISSUE TITLE
reminder: markdown recipes/tutorial for comments and description

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#124]
This is a reminder coming from [this message](https://github.com/codewars/docs/issues/67#issuecomment-675063596) in [Finish the Markdown reference/tutorial](https://github.com/codewars/docs/issues/67):

(B4B)
> * Do you (plural) think we need a tutorial or recipe about markdowns yet?
> * If so, do we make it a stand alone thing, or do we rather incorporate it to something else (like, writing descriptions)?

(kazk)
> Not really for Markdown itself, but I think we should have something for "how to write comments effectively" and also "how to write kata descriptions". For kata description, we should have some recommended style (what to include, how to structure, etc).

**Comment by hobovsky** [comment]
This issue could be split as suggested by kazk into two, and the one related to descriptions could be used as a part of breakdown for #138.

**Comment by kazk** [comment]
For "how to write comments effectively", we can do a Codewars version of [Getting Answers](https://www.mikeash.com/getting_answers.html) (or [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)). We should have something to point to with good examples when we have a user who doesn't know how to ask a question or opens issues too quickly. We can also show this before their first comment in the future.

**Comment by hobovsky** [comment]
Broken down into #142 and #143.
