### ISSUE TITLE
Authoring guidelines: descriptions

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#143]
Breakdown of #139.

Any ideas and/or links to existing stuff are welcome.

> For kata description, we should have some recommended style (what to include, how to structure, etc).
>
> https://github.com/codewars/docs/issues/67#issuecomment-675063596

I will also include a note that not all guidelines fit all types kata and some of them can be ignored if not applicable.

Proposed guidelines:

- Some of these guidelines do not apply to every type of kata. Use where applicable, so not use where not.
- Keep as language neutral as possible
- Descriptions should be written in English. Proofread, ask for help if necessary.
- Ask others if it's clear enough, consider their suggestions
- Formatting
  - use formatting, markdown, katex for readability. Avoid visual noise and excessive formatting. Consider proper header levels.
  - avoid HTML
  - use language code blocks
  - avoid descriptions mentioning many languages. use conditional blocks (link) for language specific parts.
- Requirements
  - Describe all requirements and edge cases, leave no surprises
  - Provide examples, use images when helpful. Avoid "see sample tests for more examples".
  - Describe or hint the difficulty: input ranges, volume of tests, minimum expected complexity, etc.
- Structure
  - split the description into meaningfull sections. Example:
    - overwiew/context (if needed)
    - task
    - input/output
    - rules/details
    - notes / technical details
  - try to regroup informations of the same kind: explaining inputs specificities at 3-4 different places isn't a good idea
  - the task section must stay _**short**_. Its goal is only to give an idea about what's going on. Going right there into details will just lose the user. So stay consise but precise.
  - it's generally better to explain going from general things to details/exceptions/edge cases. Not the opposite.
- Other
  - links to knowledge (hints, algorithms, papers)
  - link related problems (variants, difficulty tiers)
  - give credit when necessary
  - include Preloaded

**Comment by Blind4Basics** [comment]
We could add some tips about how to structure the content:

* split the description into meaningfull sections. Example:
  * overwiew/context (if needed)
  * task
  * input/output
  * rules/details
  * notes / technical details
* try to regroup informations of the same kind: explaining inputs specificities at 3-4 different places isn't a good idea
* the task section must stay ___short___. Its goal is only to give an idea about what's going on. Going right there into details will just lose the user. So stay consise but precise.
* it's generally better to explain going from general things to details/exceptions/edge cases. Not the opposite.
* it's sometime hard to be in the head of the reader. Especially after spending a long time writting the description. So users suggesting changes have a good chance of making good suggestions because when they read the desctiption, they don't have the whole puzzle in mind already. Hence they can see if things aren't described in appropriate order or not more easily than the author.


Note: this description of what is/should be a description doesn't fit some specific kind of katas. So a note to temper all of this might be a good idea

**Comment by hobovsky** [comment]
> Note: this description of what is/should be a description doesn't fit some specific kind of katas.

Yup, there's [this section](https://github.com/codewars/codewars.com/wiki/Tutorial%3A-Create-Your-First-Kata#assess-the-right-quality-for-the-right-kind-of-kata) in existing tutorial, I'll think how to incorporate these ideas.

> - try to regroup informations of the same kind: explaining inputs specificities at 3-4 different places isn't a good idea

Not sure I get it, what information is now specified in many places? can you give an example?

> - split the description into meaningfull sections.

I don't like this approach as a general guideline for a couple of reasons:
_[... thinks for a minute...]_
No, actually it's OK. What I don't like is the layout used by CW when sections are organized with markdown headers. Spacing is terrible. I am just not sure if that's because how headers are styled, or how users (mis)use them.

**Comment by Blind4Basics** [comment]
> Not sure I get it, what information is now specified in many places? can you give an example?

XD  -> that was something to atully write in the doc, not something about your previous message x)

herader: those?

```markdown
# Task

# Inputs/outputs
...
```

?

**Comment by hobovsky** [comment]
> XD -> that was something to actually write in the doc, not something about your previous message x)

Ah ok, I get it now :) good point.


> herader: those?

Yes. I don't know what's the cause, if it's how authors misuse the headers and do not structure their descriptions w.r.t. markdown guidelines, or maybe how they are styled with CSS, but usually, as I see in descriptions, attempts at creating some sections end up with a mess of spacing, large vertical blank areas etc. Or maybe I remember things wrong?

But the structuring itself is a good point, sure.

**Comment by Blind4Basics** [comment]
[does it look so bad?](https://www.codewars.com/kata/5aba8546379d20b9970001e4)

**Comment by hobovsky** [comment]
IMO yes. I think that hierarchical document structure does not really fit for describing a CW task. `h1` is useless, because you do not need a title here, and `h2`, styled the way they are now, are too distinctive to serve as separators for sections.

But as I said, it's only my opinion, and it does not change the fact that description has to be structured in some way, and that the structure proposed by you is good. I just don't like the styling.

**Comment by Blind4Basics** [comment]
(maybe the fact that my screen is 2560x1440 helps, on my side... x) )

**Comment by kazk** [comment]
`h1` should never be used in kata description.
`h2` can appear awkward when each section is short.
`h3` should look good in most cases. If any of the section need sub headings, then starting from `h2` can be better.

**Comment by hobovsky** [comment]
When lower level headers are not enclosed by a higher level header,  can it cause any issues with layout or anything else? If I got you right, I can use only h3 for organization and leave out h1 and h2 completely, right?

**Comment by kazk** [comment]
No, it won't cause any issues.
`h2` can be used if more depth is needed.

**Comment by DonaldKellett** [comment]
> `h1` should never be used in kata description.

I often like to repeat the title of the Kata right at the very beginning of the Kata Description (as in [here](https://www.codewars.com/kata/5b2771fab6989dd87d0000f1)) and use `h1` for it, but use `h2` or below for everything else. Should that be considered an issue?

**Comment by hobovsky** [comment]
I am not sure if I would say it's an issue, but I believe that if it was me reviewing it, I would suggest reformatting. For me, anything above `h3` messes up the flow because of large letters and very wide spacing.

But I would not fight about it, if it's ok for others then I can live with it.

**Comment by kazk** [comment]
@DonaldKellett I'd recommend avoiding repeating the title because it's redundant. I just don't understand why you need it, so can you explain?

I think `h1` is too much. But I can live with it as long as you don't use them for section headings.

```markdown
BAD! Just wrong
# Section 1
# Section 2

OK. Redundant info, possibly too much vertical space.
# Title
## Section 1
## Section 2

BETTER
## Section 1
### Sub 1
## Section 2

or

### Section 1
### Section 2
```

**Comment by DonaldKellett** [comment]
Got it, thanks for clarifying. It's mostly just a pet peeve of mine but I'll try to avoid it in future Kata I author.
