### ISSUE TITLE
Authoring guidelines: creating kata

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#149]
Breakdown of #139

Set of guidelines related to writing a new kata.

Should focus mostly on the concept of the kata itself, and link to articles related to specific parts (tests, description).
Use existing resources:
 - [Current tutorial](https://github.com/codewars/codewars.com/wiki/Tutorial%3A-Create-Your-First-Kata)
 - maybe some parts of [hobovsky's idea?](https://docs.google.com/document/d/1HencaZSAqmQvi05lHSClsuE2AxvOhwjcgEe2ChHnoJ0/edit)

Suggested guidelines:

- Task
  - Requirements and design should hold to generally accepted and widely recognized guidelines related to software design, programming, and topic of the kata. If any of these guidelines are broken, the description should justify it with a plausible explanation.
  - avoid duplicates, use new idea. Do not use problems from other sites.
  - avoid distractions, keep kata focused on one task
  - make requirements very clear, describe everything what will be tested. leave no surprises (unless puzzle).
  - if kata task is not language specific, use ideas which can be easily translated. Like, avoid mixed return types, because they are difficult to have with statically typed languages.
  - something about pointless, wrong, or untestable requirements: rounding, API restrictions, 
- Review
  - All code snippets should conform to their set of guidelines, including coding guidelines (add links)
  - make kata complete before publishing it. Do not "I will add this later".
  - share links to draft before publishing to get early feedback
  - let others help you, use gitter
- Maintenance
  - maintain your kata
  - existing solutions should be considered, but also should not be used as an argument for bad quality. Fixes which invalidate solutions are OK. Try to make fixes backwards compatible, if possible. For existing kata fix bugs, style can wait. For beta kata, invalidate everything if necessary.
  - issues and kata bugs should be fixed. when for some reason a reported issue is not going to be fixed, clearly explain why. If some issue is reported often but is not going to be fixed, put a note in the description how to work around it. Do not resolve valid issues, leave them for others to fix.

**Comment by hobovsky** [comment]
This is the next topic which I would like to tackle, and I expect it to be quite big. @codewars/community every hint and idea counts!

**Comment by Blind4Basics** [comment]
task:

* good katas are generally created wrapping code around the original idea, and not twisting the description/task around the code (that's for easy katas)
* avoid antipatterns. For example, a wrong input is supposed to raise an error/exception, not to return -1 or `"oops"` or ...

responsibility:
* write maintainable code. Once you'll quit CW, other users will have to handle your mess... XD


---

* maybe to state that the language to use is english?

**Comment by hobovsky** [comment]
> * good katas are generally created wrapping code around the original idea, and not twisting the description/task around the code (that's for easy katas)

I am not sure if I agree in general, and I think that kata created "code first" can also be good. But still, I can see how noob authors are getting it wrong. I will think how to word it.

> * avoid antipatterns. For example, a wrong input is supposed to raise an error/exception, not to return -1 or `"oops"` or ...

Yup.

> responsibility:
> 
> * write maintainable code. Once you'll quit CW, other users will have to handle your mess... XD
> * don't approve translations without questions, especially if you don't know the language (?)
> * maybe to state that the language to use is english?

These will be mentioned in related parts (coding, translations, descriptions).

**Comment by hobovsky** [comment]
PR merged, please open a new issue if you find any problems or have more suggestions.
