### ISSUE TITLE
Authoring guidelines: general

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#161]
Breakdown of #139 

This part would be a set of guidelines related to authoring activities in general, which would have to be followed by every type of content and every author. I am not sure yet if there will be enough of them to create separate section, but let's see.

Proposed guidelines:

- preface
  - why do we need these guidelines 
  - authoring of good content is difficult, even for easy problems 
- Meta
  - should be followed rigorously for new and beta kata and pending translations
  - can be relaxed for existing content. use common sense, accounting for severity of the issue
  - all types of guidelines should be followed where applicable, and can be ignored where not.
  - should be used by authors while writing, and for reviewers before approving
  - ... somehow encourage users to participate in reviews
  - in severe cases, authors and reviewers who do not comply can have their authoring or approval privileges revoked, and offending content can be withdrawn.
- Quality
  - do your best, stick to guidelines specific to the type of created content (kata, translation, snippets, ...)
  - When reviewing, do it properly.
  - you keep responsibility for all content you approved or created. Fix issues, consider suggestions, answer questions.
  - if your content does not keep up to quality standards, others are allowed to improve it
  - when in doubt, ask for help
  - easy tasks should be of good quality too

Do you think such set of general rules will be OK?

**Comment by Blind4Basics** [comment]
I guess so, but not sure it needs to be separated from CoC. => ?

**Comment by hobovsky** [comment]
I think CoC is more about relations between community members, like be nice, don't cause harm, etc. This one is strictly about content, i an not sure if these two belong together.

**Comment by hobovsky** [comment]
I am thinking about adding a guideline which would state that existing solutions should not prevent improvements.  But I am not sure what should be the extent of such guideline. For example I am not sure if renaming a function because its name does not conform to PEP is sufficient reason for 4 years old kata with 3k of solutions. OTOH there are many old kata with many solutions which definitely should be fixed because they are simply broken and possible to pass only because of hints available in discourse.

What do you think?

**Comment by Blind4Basics** [comment]
sounds like another section about "maintaining kata", imo.

**Comment by hobovsky** [comment]
Could be, yes. But having it here in the official (I hope) guidelines would make it (as suppose) enforceable and could be used as an argument for authors who say that "yeah I know there's a problem, just resubmit 5 times and it will pass. I won't fix it because there's 1000 of solutions".
Point them to the guideline, ask politely to comply, and if it does not help, fix it by yourself.

**Comment by hobovsky** [comment]
Also maybe something about sticking to the guidelines rigorously for new content, and somehow easier for the old kata? I am not sure how to approach this, I imagine there could be some people wanting to fix some old, bugged kata and possibly call out the guidelines to finally be able to do this. Should they be allowed to so?

**Comment by Blind4Basics** [comment]
I'd say there are several things at stake, here:
* what to do about minor "bugs"?
* how lax to be about those minor "bugs"?
* what to do about major bugs? (here it's easy: fix them)
* critical part: when does a problem fall into one or the other category?

As usual when it comes to this, the main problem will actually be that people will disagree. And with a lot of energy (why do I think about FArekkusu, suddenly? x) Well, I bet I fit into the categro as well...). So even with a direction, differences in interpretation will be huge. 

So I'd just stay pretty "vague". Something like

> Bugs need to be fixed. Even if discovered long after the approval. Other things, if not harmful for the kata (like wrong naming conventions) __could__ be fixed, especially when it's possible to do so without breaking old solutions, but it's not mandatory. Tho, if the author doesn't want to fix it himself, he'd have to suffer the presence of the related issue(s), so that a PU can go by and fix it if he wants.

?

Ofc, @kazk opinion here is of critical importance. => ?

**Comment by hobovsky** [comment]
Maybe try and differentiate somehow between bugs (which prevent valid solutions from passing in some way), and style (naming, coding conventions)?

We have two opposite sides here: one side is authors not wanting to comply (mentioned already [in this post](https://github.com/codewars/issues/issues/49#issuecomment-720781023) ), and another is (over)eager reviewers and users fed up with poor quality going edit-frenzy because now they finally **can**.

I am not really sure how to address it in guidelines.

**Comment by Blind4Basics** [comment]
Sounds to me like people related, hence, s a lost cause up front...? x)

Not really sure what to suggest. But if people have to comply in a way or another, there is one sure thing: there need to be some kind of (meaningful) consequences if they do not comply. And not just a bunch of honor points. Otherwise ntohing will "move".

**Comment by kazk** [comment]
> I am thinking about adding a guideline which would state that existing solutions should not prevent improvements.

Yeah, in general, invalidating existing solutions should not prevent improvements. If it's possible to make the change backwards compatible without too many hacks, it should be considered though.

Sometimes the issue is relatively minor and a fix is not really worth it. Those should include a disclaimer in the description acknowledging the issue so the new users will know it's a known issue and it's not fixed because of historical reason.

> OTOH there are many old kata with many solutions which definitely should be fixed because they are simply broken and possible to pass only because of hints available in discourse.

If the solver needs to dig through the comments, then that information should be included in the description. It's much more efficient for the authors too, so I don't understand why they decide to keep replying to similar comments over and over instead of improving the description.

> So even with a direction, differences in interpretation will be huge.

Having clear guidelines should help.

> But if people have to comply in a way or another, there is one sure thing: there need to be some kind of (meaningful) consequences if they do not comply. And not just a bunch of honor points. Otherwise ntohing will "move".

Yeah, that's what I've been concerned about.
As I've been saying, it's difficult to start enforcing some rules after so many years of chaos. I don't expect this to go smoothly at all, but we need to start it.

**Comment by hobovsky** [comment]
> If the solver needs to dig through the comments, then that information should be included in the description. It's much more efficient for the authors too, so I don't understand why they decide to keep replying to similar comments over and over instead of improving the description.

Sometimes, even having hints in description how to work around issues should not stop the kata from being fixed at (almost) any cost. Sometimes the explanation is in the description, but this explanation is something like "if you keep failing due to precision errors, try reordering operations in your formula". All issues are insta-closed because, uh, excuses are many: "it's user error", "it works if you do things in good order", "there are 2k solutions so kata is ok", "there are 2k solutions so it's too late to fix it".

Yeah, kata with issues related to FP precision, rounding, handling floats as strings, these are particularly fun :) both to solve, and to fix.

**Comment by hobovsky** [comment]
Closed with #173
