### ISSUE TITLE
Rewrite Python Test Framework docs

### ISSUE THREAD

**Issue by kazk** [codewars/docs#17]
* [x] reference
* [ ] guide/tutorial

---

We currently have two Python test framework docs.

- https://github.com/codewars/docs/blob/master/wiki/codewars-python-test-framework.md
- https://github.com/codewars/docs/blob/master/wiki/codewars-python-test-framework-v2.md

Based on these, we should create:

- A guide for writing good tests with it (read few times when starting)
- A reference manual you can refer to (read multiple times)

The guide should describe how to write tests. The reference should list all the assertion functions and example usages.

Later, we can also add another page for specific topics, e.g., writing random tests.

Feel free to comment for any thoughts. Also, assign yourself to let the other members know you're going to work on it.

**Comment by Blind4Basics** [comment]
do we agree to describe only v2? (sying that v1 still exists in old katas should be enough. Only PUs will be facing old codes to maintain anyway, I guess)

I'll begin with the reference manual. How do I proceed? pull request on doc.codewars, I guess?

**Comment by Blind4Basics** [comment]
BTW, now that we're talking about it... Should we add my module forbidder to the test framework? That would require some work, but it's already in the wild in a lot of katas and it's spreading. And it has some flaws and it already became impossible to update it everywhere, since I don't know all the places... :/

(yeah, it's "a bit" off topic... x) )

**Comment by kazk** [comment]
Yeah, focus on the v2. We can add some notes about the old one later.

For module forbidder, can you open a new issue at https://github.com/codewars/python-test-framework?

**Comment by Blind4Basics** [comment]
done

is that repo the last version? (I believe not?) I'd like to have the code on hand so that I can check what I write about it. XD

**Comment by kazk** [comment]
Yeah, it's the version being used on Codewars.

**Comment by Blind4Basics** [comment]
:+1:

**Comment by Blind4Basics** [comment]
how do I integrate an picture...? :/

**Comment by Blind4Basics** [comment]
https://github.com/codewars/docs/pull/18

**Comment by kazk** [comment]
Can you move the files?

- document to `content/languages/python/codewars-test-famework/index.md`
- image to `content/languages/python/codewars-test-framework/python-test-framework-example.png`

Then, use the image in the Markdown. `![Python Test Framework Example](./python-test-framework-example.png)`.

Also, add frontmatter to Markdown so that it shows up on the Python page and navigations are added.

```
---
category: references
languages: [python]
tags:
  - testing
prev: /languages/python/
---
```

**Comment by Blind4Basics** [comment]
Ok, I'll see that tomorrow. I really need to sleep, right now.

cheers

**Comment by Blind4Basics** [comment]
Stuff to add to this part yet? Or can we close it for now?

**Comment by hobovsky** [comment]
On structuring the test suite with `describe`/`it`:

> Assertions directly in `describe` should be avoided. It happens to work at the moment, but it's awkward.
Top-level `it` should be fine. Many test frameworks don't have `describe`.
Top-level assertions are strongly discouraged.
> 
> So `describe -> it -> assertions` best, `it -> assertions` ok, `describe -> assertions` bad, `assertions` bad.

**Comment by hobovsky** [comment]
Created an issue dedicated to the guide here: #191.

**Comment by hobovsky** [comment]
@kazk  now #191 and #197 are done, do you consider anything more necessary in scope of this issue, or can it be closed?

**Comment by kazk** [comment]
This can be closed. Thanks everyone, for writing them.
