### ISSUE TITLE
Improvements to the authoring guidelines (Writing a Kata Description)

### ISSUE THREAD

**Issue by FArekkusu** [codewars/docs#176]
[Link to the article](https://docs.codewars.com/authoring/guidelines/description/).

> Descriptions should be written in English

After reading this sentence I thought there will be an explanation that CW is an international website, and that an international language should be used for kata-authoring, but for some reason that point suggests that authors should ask for proof-reading instead which is completely unrelated.

> Descriptions should provide examples of inputs and outputs for some representative scenarios. Provide as many examples as you think necessary.

In the "Structure" part it's said that examples are optional, but then in "Requirements" it's heavily suggested that examples are mandatory. Apart from inconsistency, IMO the former option is better, because people might include many examples when the underlying idea is already simple enough, and make the description considerably longer than it's needed. On top of that, I think it'd be good to mention that examples should help visualize the solution itself (like I did [here](https://www.codewars.com/kata/5e90f0544af7f400102675ca)), and not simply say

```
your_function(input_1) == output_1
your_function(input_2) == output_2
your_function(input_3) == output_3
```

> Description can contain links and references to external sources of knowledge, articles, explanations and papers. Keep in mind that external links create dependencies. Links that change over time may render a kata unusable and introduce a maintenance issue

It should be stated that descriptions are supposed to be self-contained, and users should be able to solve the task without relying on any external resources at all (i.e. "read this if you need an in-depth explanation", and not "read this because I was too lazy to explain the stuff you need"). Plus, whenever possible, authors should give links to the relevant info only (like concrete sections in Wikipedia articles), instead of linking a huge article where only a few sentences help you understand the idea, and the user himself has to search for it.

**Comment by hobovsky** [comment]
> [...] for some reason that point suggests that authors should ask for proof-reading instead which is completely unrelated.

Well apparently I just made a big leap forward with my thinking and assumed that since the community is international, users probably won't be fluent with English and could use someone to proofread descriptions written by them :)



> It should be stated that descriptions are supposed to be self-contained, and users should be able to **solve** the task without relying on any external resources at all (i.e. "read this if you need an in-depth explanation", and not "read this because I was too lazy to explain the stuff you need").
>
> (emphasis mine)

I am not sure if I understand you, do you mean that description should explain how to solve the kata? Could you please elaborate on this point, or explain how this remark would apply to some specific example, like [Voronoi cells](https://www.codewars.com/kata/58bf8041aa4014a09e000013) kata, or some other?

**Comment by FArekkusu** [comment]
> I am not sure if I understand you, do you mean that description should explain how to solve the kata?

Well, the "without relying on any external resources **at all**" part is too extreme and unrealistic, so I can see where the confusion is coming from.

I think, it'd be better to say that the description, regardless of the inclusion of any external links, should give users enough information to get at least minimal understanding of what they're supposed to do. For example:

* B4B's "FMC" katas are fine because all the chemistry-related stuff is explained in the description, and you only need to figure out how to implement the data structures and their methods correctly
* The "Voronoi cells" kata is fine too because it explains what voronoi cells are, includes a very helpful image for visualization, and clearly states the task, so the your job is again only figuring out how to solve the problem
* Something like [this](https://www.codewars.com/kata/5980d4e258a9f5891e000062) or [this](https://www.codewars.com/kata/5f85b9a415176b0001519083) is terrible: very specific knowledge is required from you to understand what the task is, at the same time there's virtually no explanation of what the inputs/outputs are, what you're supposed to with them, or even where you can learn what you need

**Comment by hobovsky** [comment]
I tried to address your remarks with #184 . Any feedback would be appreciated.
