### ISSUE TITLE
Create HOWTO on adding images to kata description

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#186]
Motivated by this post: https://www.codewars.com/kata/5fc5e74d8c53ff0027f00ace/discuss#5fc6cac41da1040023327e7d

I prepared some examples here: http://snippi.com/s/g4a6emp

And this kumite: https://www.codewars.com/kumite/5fc6e48caa10e60018543723?sel=5fc6e48caa10e60018543723 but it turns out not to work too well as a presentation of things related to descriptions :(

If you have any ideas what should (or should not) end up in such article, let me know.

- Mention plans on the upload functionality
- Kazk: _The description shouldn't rely on images unless it's absolutely necessary though._
- Mention drawbacks : layout, theming,  mobile users
- Copyright, licensing, IP issues
- Browser compatibility

**Comment by kazk** [comment]
I've been wanting to support image uploads for the description. Once that's done, users can paste the image directly into the editor. But I don't know when I'll be able to work on that yet. I'd also like to support a way to specify image for light/dark theme, similar to the docs.

The description shouldn't rely on images unless it's absolutely necessary though.

---

Kumite descriptions are rendered by the server and have different behavior, so you should create a draft kata if you want to provide a live example.

**Comment by hobovsky** [comment]
So maybe I should hold on with this article and do not create it until uploading is possible?

**Comment by kazk** [comment]
You can write it. I don't think I can work on it for a while.

When the feature is ready, we can say that's the preferred way, but inlining will continue to work. Just mention not to embed huge images.

**Comment by hobovsky** [comment]
- Mention drawbacks : layout, theming,  mobile users
- Copyright, licensing, IP issues

**Comment by hobovsky** [comment]
@codewars/community @ggorlen 

I published a PR (#187) with an initial version. Examples are deliberately somewhat sparse, to show how problematic working with images can be, but maybe they should be improved?

**Comment by hobovsky** [comment]
From this review comment: https://github.com/codewars/docs/pull/187#issuecomment-748464654

> about the `data url` part, the way to create them should be provided too (maybe just an external link?)
> 
> edit: or maybe, put the inlining svg § first, if the underlying goal is to not lead the users to use data urls.

@Blind4Basics what do you mean exactly by _way to create them should be provided too (maybe just an external link?)_ ?
My idea here was not to spoonfeed users, just to point them in a direction and hope they could take it from there. Do you think examples present there are not enough?

**Comment by Blind4Basics** [comment]
Not sure... If the goal of the docs is to actually give all useful info, I think this should be given too. On my side, Idon't know how to create such a data url image, actually.

But again, if you prefere the idea of using the "svg stuff" rather tha "data urls", that's fine. I'd just push that § above the data url one.

**Comment by hobovsky** [comment]
You think a link to some tool, like this one: https://ezgif.com/image-to-datauri would be ok?

**Comment by Blind4Basics** [comment]
:+1:

**Comment by hobovsky** [comment]
Added some examples of tools, let me know if something needs improvements.

I also thought about mentioning Unicode characters, for example chess pieces to draw a chessboard. Do you think it would be good to have?

**Comment by Blind4Basics** [comment]
Possible, yes, but not in the "image embedding" part x)
Tho, I guess it's a bit specific, so just talking about them with some examples might be enough, yes (I'd put that in the section(s) about writing descriptions, but that's useful in testing feedback too, so....?)
