### ISSUE TITLE
Guide on creating kata in Python

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#191]
Breakdown of #17.

Many collected ideas are not really language specific, so maybe they will get extracted to some common part. I will see how it goes when more languages gets added.

Any ideas are welcome!

**Comment by hobovsky** [comment]
On structuring the test suite with `describe`/`it`:

> Assertions directly in `describe` should be avoided. It happens to work at the moment, but it's awkward.
Top-level `it` should be fine. Many test frameworks don't have `describe`.
Top-level assertions are strongly discouraged.
> 
> So `describe -> it -> assertions` best, `it -> assertions` ok, `describe -> assertions` bad, `assertions` bad.

**Comment by XRFXLP** [comment]
These kata implements quite hard-to-bypass module forbidding in python:
+ https://www.codewars.com/kata/5c9a6e225ae9822e70abc7c1
+ https://www.codewars.com/kata/5791bdba3467db61ff000040

**Comment by XRFXLP** [comment]
There are a number of katas in which a preloaded helper/aiding function is given to the user for example `encode` in [this](https://www.codewars.com/kata/52cf02cd825aef67070008fa) kata, but usually translators, authors, and reviewer miss this point that function can be inspected and mutated.

This should be avoided by redefining the function in the full test suite.

**Comment by hobovsky** [comment]
Notes on preloaded and its visibility are here: https://docs.codewars.com/authoring/guidelines/preloaded/#accessibility-of-preloaded-code
