### ISSUE TITLE
Create a guide for authoring in C

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#207]
Create an article similar to https://docs.codewars.com/languages/python/authoring/ but for C.

Points needing particular attention:
- ~~memory management: show possible ways, common pitfalls, good practices~~ - moved to separate article
- assertions: Criterion assertions are macros with poor default messages
- includes
- bloated preloaded
- compilation warnings
- random utilities, `RAND_MAX`, `srand`

**Comment by ggorlen** [comment]
There's a small walkthrough on improving criterion assertion messages [here](https://www.qualified.io/kb/languages/c/criterion) which may be useful.

**Comment by hobovsky** [comment]
Thanks, can be useful when I start working on #232 👍
