### ISSUE TITLE
Create a guide for authoring in Ruby

### ISSUE THREAD

**Issue by Steffan153** [codewars/docs#215]
Create an article similar to https://docs.codewars.com/languages/python/authoring/ but for Ruby.

**Comment by hobovsky** [comment]
@Steffan153 is there anything to do on #252? I think the example test suite is missing?

**Comment by Steffan153** [comment]
Yep that's all that's left.

(Looks like I wasn't noticing all these notifications.)

**Comment by hobovsky** [comment]
You need help finishing it?

**Comment by Steffan153** [comment]
No, I can do it.
