### ISSUE TITLE
HOWTO access text of submitted solution

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#222]
As mentioned in #65 

> This needs a dedicated page. It's always at `/workspace/solution.txt` for any language. Older language versions have `/home/codewarrior` symlinked to `/workspace` so `/home/codewarrior/solution.txt` works on those, but should be updated to `/workspace/solution.txt`.

- explain current location,
- mention `/home/codewarrior/` being deprecated,

@kazk do you have any idea where to put such article in current docs and how to classify it?

Is encoding of the file known? it can be meaningful when reading it as text (as opposed to byte size when read as raw bytes).

**Comment by kazk** [comment]
> @kazk do you have any idea where to put such article in current docs and how to classify it?

Probably under `authoring/kata/` as `recipe`.

> Is encoding of the file known?

Always `utf-8` (Node's `Buffer.from(string)`)
