### ISSUE TITLE
Working with floating point numbers

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#242]
Create a tutorial explaining why floating point numbers are difficult to work with, what problems they cause in kata, and how to avoid pitfalls related to them when authoring a kata.

Maybe the tutorial might be not limited only to authoring, but could be made useful also for users encountering problems while training?

- precision loss, non-associativity, conversions
- comparison, assertions 
- formatting (also in assertion messages)
- alternatives
- rounding, and why not rounding. Rounding modes

**Comment by hobovsky** [comment]
I've decided to hide the "why" section and I will probably remove it, because it seems to introduce too many details. But still I do not like the fact that it will probably strip the article from its educational aspect.

@kazk could you hint some good location for the article files in the repo?

All reviews are appreciated, and any remarks are welcome.

**Comment by kazk** [comment]
Under `/authoring/kata/` like you have should be fine for now.

**Comment by imjasonmiller** [comment]
I would definitely appreciate some code examples for authors regarding assertions. While I've used `approx` myself for approximate float comparison, there are a few others crates that seem to do the same in Rust:

* [approx](https://github.com/brendanzab/approx)
* [float-cmp](https://github.com/mikedilger/float-cmp)
* [float_eq](https://github.com/jtempest/float_eq-rs)

The author of `float_eq`, the newest crate, [expanded on the differences](https://www.reddit.com/r/rust/comments/fzwxiy/announcing_float_eq_for_explicitly_bounded/) between it and the other listed crates.

I'd be interested in hearing what others have to say, perhaps @error256?

**Comment by kazk** [comment]
> The [`approx`](https://lib.rs/crates/approx) and [`float-cmp`](https://lib.rs/crates/float-cmp) crates provide a similar style of general comparison operations, whereas [`assert_float_eq`](https://lib.rs/crates/assert_float_eq) focuses specifically on assertions. The [`almost`](https://lib.rs/crates/almost) crate instead divides its API into algorithms comparing against zero and non-zero values. In contrast, [`efloat`](https://lib.rs/crates/efloat) takes the approach of tracking the error bounds of values as operations are applied.
>
> https://github.com/jtempest/float_eq-rs#related-efforts

**Comment by hobovsky** [comment]
I'd be reluctant to put too much language-specific information in this article. I tried to keep it to the minimum, and mention only some notable exceptions.

If you are interested in having something specifically for Rust, you can create a page similar to this [Python](https://docs.codewars.com/languages/python/authoring/), [JavaScript](https://docs.codewars.com/languages/javascript/authoring/) or [C](https://docs.codewars.com/languages/c/authoring/) tutorial.

Maybe I should somehow mention that language-specific information should be looked up in the reference for the used framework, on on language-specific pages of docs.

**Comment by kazk** [comment]
@imjasonmiller Can you open a new issue about adding one of them in the runner repo? I haven't done anything with floating point in Rust, so I have no idea.

**Comment by hobovsky** [comment]
I am still not sure whether the part _"Strange things about floating-point values"_ (currently hidden in the collapsible section) should be kept, or is it too detailed. What do you guys think?
