### ISSUE TITLE
Floating-point comparisons in Ruby

### ISSUE THREAD

**Issue by Steffan153** [codewars/docs#253]
Snippet for doing floating-point comparisons in Ruby.

**Comment by hobovsky** [comment]
I would expect #242 to cover this topic in general, mentioning some rationale of the program, handling FP numbers in kata, solutions, and assertions.

Do you think it requires some special attention in Ruby? Is it any different than handling any other IEEE-754-compliant language?

**Comment by Steffan153** [comment]
Well, JS and Python have functions already built-in to the test framework. Ruby doesn't. I thought it would be nice to make a **snippet** (not a recipe) including an already-made function to do this.

**Comment by hobovsky** [comment]
You mean assertions?

If so, then yes, sounds as a good idea.

**Comment by Steffan153** [comment]
Yes, assertions. If kazk wants to, maybe we could add it to the existing test framework when Ruby 3 is added.

**Comment by kazk** [comment]
Ruby test framework is open sourced here: https://github.com/codewars/ruby-test-framework
Please open PRs for new assertions.

Ruby 2.5 on Codewars doesn't use this. I made the repo when I was preparing for a new Ruby version to use proper package management...

I'd like to migrate to RSpec in the future, but have no idea when that will be.

**Comment by kazk** [comment]
From Ruby 3.0, you can use [`be_within` matcher](https://relishapp.com/rspec/rspec-expectations/v/3-10/docs/built-in-matchers/be-within-matcher) from RSpec.

```ruby
expect(actual).to be_within(0.001).of(expected)
```

**Comment by hobovsky** [comment]
Superseded by #455
