### ISSUE TITLE
JS snippet to handle JSON.stringify bug with BigInt builtins

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#257]
see [here](https://www.codewars.com/kata/6001524cf7cb88000e675acb/discuss/javascript#600f4b23d0e6ff00117d774e)

**Comment by hobovsky** [comment]
Quoting the original post:


> One problem with `BigInt` is that `JSON.stringify` doesn't support it. Failure messages will throw a `TypeError`.
> 
> To make them look like this:
> 
> > expected { BigInt: '123252' } to equal { BigInt: '123251' }
> 
> insert these two lines in Preloaded:
> 
> ```
> Object.defineProperty( BigInt.prototype, "toJSON", { value: String } );
> Object.defineProperty( BigInt.prototype, "BigInt", { get() { return String(this); }, enumerable: true } ) ;
> ```
> 
> With that, you can use `assert.strictEqual` normally.
> 
> ( I just now figured this out. In my own kata, I used to use something much more involved. )

**Comment by hobovsky** [comment]
It seems this error has been fixed in Mocha a couple of days ago: https://github.com/mochajs/mocha/pull/4112

@kazk do you think the snippet proposed in the initial post would be useful, or it would be possible to update Mocha?

**Comment by kazk** [comment]
It's possible to update Mocha for Node v12 when it's released, as long as it's Mocha v8.x (no breaking change) or if we're sure any breaking changes won't affect Codewars and Qualified users.

**Comment by hobovsky** [comment]
It just got released: https://github.com/mochajs/mocha/releases/tag/v8.3.0

Should I create an issue in runner repo for update of Mocha?

**Comment by kazk** [comment]
Yeah, I'll try to update soon, but having an issue for it is a good idea.

**Comment by hobovsky** [comment]
Workaround is no longer needed as the issue got fixed directly in Chai: https://github.com/codewars/runner/issues/146
