### ISSUE TITLE
Error in JavaScript: creating and translating a kata # Example test suite

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/docs#261]
The code example in [JavaScript: creating and translating a kata # Example test suite](https://docs.codewars.com/languages/javascript/authoring/#example-test-suite) has `(actual,expected)` in the wrong order in the `"Fixed tests"` section of the test suite.

In the section above that, the correct order is specified, and the `"Random tests"` have arguments in the correct order. The offending section is probably just a copy/paste from another language with slightly inadequate proofreading.

**Comment by hobovsky** [comment]
Fixed. If I still missed something, reopen this issue and let me know.
