### ISSUE TITLE
Document Math typesetting extension for kata descriptions

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#27]
I guess everything is in the title...

**Comment by kazk** [comment]
No, I don't understand what you mean. Can you explain?

Are you requesting to support some Math typeset for writing documentation?

**Comment by kazk** [comment]
If you mean documenting the Markdown extension for kata descriptions, we need to rewrite the Markdown doc from the wiki first.

**Comment by Blind4Basics** [comment]
ah sorry.

I know (at least I blieve I know... :o ) that you  (?) introduced recently a way to write mathematical equations in the descriptions (iirc, @DonaldKellett requested it). For those who don't know how to use that stuff, we need to add the related documentation.

clearer?

**Comment by kazk** [comment]
Yeah, thanks. That should be added to the Markdown doc and mention that it only works for kata descriptions at the moment.

**Comment by Blind4Basics** [comment]
https://github.com/codewars/codewars.com/issues/1527 infos to write the documentation
