### ISSUE TITLE
Fix styling of info boxes

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#281]
Info boxes are now styled with very intense colors, and stand out very prominently, especially in dark mode:

- `note` is almost white on black
- `warning` is very aggressive red

I think other boxes are not used currently, but it would be worth to review them too. I generally liked their styling from before the migration a lot.

![image](https://user-images.githubusercontent.com/23709795/114840076-bb8bde00-9dd6-11eb-8c34-3ab9ca58e36f.png)

![image](https://user-images.githubusercontent.com/23709795/114840132-c777a000-9dd6-11eb-91b0-78d43b69d2dc.png)

**Comment by kazk** [comment]
The previous versions for reference:
![image](https://user-images.githubusercontent.com/639336/114846669-c2dcc880-9d91-11eb-99a0-9b716617ecc8.png)
![image](https://user-images.githubusercontent.com/639336/114846689-c708e600-9d91-11eb-804f-13158f861444.png)
