### ISSUE TITLE
Consider distinct favicon for docs

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#282]
I liked it more when favicon for docs was different than favicon of the main site:

![image](https://user-images.githubusercontent.com/23709795/114841496-3275a680-9dd8-11eb-91c0-64651ed9ec7c.png)

This way I do not mix up tabs when having a ton of them open. I usually keep one tab to docs open somewhere to copy links to it when answering questions, and now I cannot find it :)

**Comment by kazk** [comment]
Wait, did it change? I didn't mean to.

I might have copied the favicon from Codewars when I was playing with Docusaurus, and continued to used that when merging.

**Comment by kazk** [comment]
Apparently, the old one was generated from a PNG file by the framework.

We might want to make something more clearly distinct. https://realfavicongenerator.net/ can be used to generate one.

Any suggestions?

**Comment by hobovsky** [comment]
I was thinking about a family of icons where the current one from the main site would be a base one, and accompanying sites like blog, docs (maybe even gitter chat and github repos, if possible?) would use the same base icon but with some specific overlay or additional mark or something.

I am not sure if it's doable though, the last time I checked favicons were 16x16 BMPs :)

**Comment by kazk** [comment]
> (maybe even gitter chat and github repos, if possible?) 

No, that's not possible.

---

For now, I'll change to this:

![image](https://user-images.githubusercontent.com/639336/115498645-cf926e00-a222-11eb-9863-d970d22cd115.png)

![image](https://user-images.githubusercontent.com/639336/115498729-f486e100-a222-11eb-8710-ce6d8362cf80.png)

**Comment by XRFXLP** [comment]
What about this?

![image](https://user-images.githubusercontent.com/23459568/117342810-41c0af00-aec1-11eb-891c-992fa55b9135.png)

(Created by Jason Miller)

**Comment by kazk** [comment]
Nice! @imjasonmiller do you want to open a PR? Just replace the files in `static/`.

**Comment by imjasonmiller** [comment]
> Nice! @imjasonmiller do you want to open a PR? Just replace the files in `static/`.

I'll do just that! :-)
