### ISSUE TITLE
Docs general layout: variable width?

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#33]
Currently, the width of the different pages on docs.codewars may be pretty narrow. In full screen mode, I get this:

![image](https://user-images.githubusercontent.com/32236948/87250456-23d31b00-c465-11ea-8eb7-55fcc476d46c.png)

Would be nice(r) to either:
* set the default width larger?
* make it autoadaptable to the width of the window itself?

This problem makes the glossary rather massive too: the middle column is as narrow there as it is in the picture above, making some longer definitions looking pretty... "bad" (see the preview of the PR #31 )

**Comment by kazk** [comment]
Yeah, the glossary page can be little wider. I'll adjust after merging your changes and seeing how it looks.

> make it autoadaptable to the width of the window itself?

Normal pages (generated from Markdown) are responsive and currently like this:

480

<img alt="480" src="https://user-images.githubusercontent.com/639336/87256409-17d86080-c447-11ea-8294-4bba5e299099.png" height="500px" />

640
<img alt="640" src="https://user-images.githubusercontent.com/639336/87256237-b9f74900-c445-11ea-8dc6-74dff01f70a0.png" height="500px" />

768
<img alt="768" src="https://user-images.githubusercontent.com/639336/87256238-ba8fdf80-c445-11ea-8ad2-a940a1bf627d.png" height="500px" />

1024
<img alt="1024" src="https://user-images.githubusercontent.com/639336/87256239-bb287600-c445-11ea-8716-326d110ac64c.png" height="500px" />

1280
<img alt="1280" src="https://user-images.githubusercontent.com/639336/87256242-bbc10c80-c445-11ea-8ba6-f49748149015.png" height="500px" />

1440
<img alt="1440" src="https://user-images.githubusercontent.com/639336/87256243-bc59a300-c445-11ea-9d9b-fb072c75edcc.png" height="500px" />

Your screen looks unusually wide. (I use ultrawide, but never have single window filling the screen.)

We'll adjust things as we go, but the main content shouldn't become too wide even for the super wide screen like yours. Maybe max around 100-120 characters per line.

**Comment by Blind4Basics** [comment]
yeah, right... x) My screen is 1440*2560.... XD

:+1:

**Comment by Blind4Basics** [comment]
closing.
