### ISSUE TITLE
rank up scores not updated in #docs

### ISSUE THREAD

**Issue by 0ussamaBernou** [codewars/docs#441]
i exceed the score to rank up to 5kyu, but never ranked up.
I suppose the Rank up scores are updated, but not in the docs

**Comment by isaacmcdougal** [comment]
Honor and rank score are different. Your rank score isn't listed on codewars anywhere, but you can view it with the API. The doc explaining this is [here](https://docs.codewars.com/gamification/ranks/). I just checked and you currently have 223 rank points. You need 229 to reach 5kyu.

**Comment by 0ussamaBernou** [comment]
> Honor and rank score are different. Your rank score isn't listed on codewars anywhere, but you can view it with the API. The doc explaining this is [here](https://docs.codewars.com/gamification/ranks/). I just checked and you currently have 223 rank points. You need 229 to reach 5kyu.

I see now, didn't read the docs carefully. Thanks.
