### ISSUE TITLE
formatting of the tags/references/... pages?

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#64]
### currently:

![image](https://user-images.githubusercontent.com/32236948/87763804-a36e3a80-c815-11ea-8723-25753de956de.png)

15 pages with only 4 references shown at the same time.

### expected:

to see more of them at the same time (but how much??)

**Comment by kazk** [comment]
Yeah, I had it set to small number to test the pagination. 
We still need to decide how to present these links and I’ll adjust the number then.

**Comment by Blind4Basics** [comment]
Nicer, thx.

Tho, I'm still wondering... (hence I changed the title):

I doubt that having those links will actually be that useful. I mean, once the search engine will allow to search for tags, references, recipes and tutorials, I guess nobody will actually stalk for a link in the page themselves once there are a lot of references. So I'm wondering if having those pages as they currently are is actually useful. For example, the icons in the home page could instead link to a search page where the related flag would already be set (just like in the cw's issue repo: `is:open`). 

This train of thoughts leads me to the same idea I already talked about: I'd really like to see, as a user, a real "table of content". For those who wanna grab an idea of the whole content of the documentation, in a "somewhat ordered fashion". Because the main problem of search engines is that, if you don't know a page/info exists, you have close to no chances to actually find it.

**Comment by kazk** [comment]
As I said before, we'll adjust as we have more documents. We might end up removing them, I don't know yet. I'm not against some kind of overview page either. But we need to have more contents first to find what works.

> Because the main problem of search engines is that, if you don't know a page/info exists, you have close to no chances to actually find it.

Can you elaborate? I'm not sure why you need to know if the information exists.

Have you used documentation with DocSearch (which we'll switch to after having more content #4)? For example, see [VueJS](https://vuejs.org/v2/guide/). Type whatever you want to know and it'll show you related results as you type. This doesn't require one to know that the page exists.

**Comment by Blind4Basics** [comment]
DocSearch: nope never used it.

exist/doesn't exist: My idea is rather the opposite one, not searching for something because one might have no idea it's present in the documentation.

ok, we'll see later about that. :+1:
