### ISSUE TITLE
Show screenshots matching the theme

### ISSUE THREAD

**Issue by kazk** [codewars/docs#71]
For some screenshots, it might be better to use the version matching the current theme (dark mode on/off).

This should be possible using `dark:hidden` and `dark:block` variants:

```markdown
<div class="block dark:hidden">

![alt](./light.png)

</div>
<div class="hidden dark:block">

![alt](./dark.png)

</div>
```

Wrapping in `<div>` because we can't use `<img>` tag with relative paths in Markdown at the moment.

**Comment by Blind4Basics** [comment]
info for later: once it works, remove this file: 

` docs/content/languages/python/codewars-test/python-test-framework-example.png `

**Comment by Blind4Basics** [comment]
done here, archived in #74
