### ISSUE TITLE
change the "selection highlightening" color, in code blocks

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#77]
### Currently:

when selecting code in code blocks, the background is very dark and the selection is "highlightened" in dark brown, making it close to invisible (it's even worse in light mode, since the outer background is making the selection harder to see).

![image](https://user-images.githubusercontent.com/32236948/87924523-4e356180-ca7f-11ea-8de9-c7e30404f851.png)

### Expected:

something with "higher contrast"...

**Comment by kazk** [comment]
It's "Material Oceanic" theme from https://github.com/PrismJS/prism-themes . We can change to other themes too (or possibly switch to using CodeMirror like Codewars).

The selection background is currently `#363636`, changing that to `#727272` will look like:
![image](https://user-images.githubusercontent.com/639336/87968597-8768d400-ca75-11ea-8592-c0b8749342a1.png)

**Comment by Blind4Basics** [comment]
:+1:
