### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by kazk** [codewars/docs#9]
Add `data/glossary.yml` listing Codewars terms and definitions. Generate a page from it and reference to it from other documents.

**Comment by Blind4Basics** [comment]
is it `.yml` or `.yaml`? I found the former but not the latter.

example reference I found [here](https://github.com/google/WebFundamentals/blob/master/src/data/glossary.yaml):

```
##
## Please add new terms in alphabetical order.
##

# EXAMPLE
# - term: Progressive Web App (REQUIRED)
#   description: A progressive web app is awesome. (STRONGLY ENCOURAGED) (HTML permitted)
#   acronym: PWA (OPTIONAL)
#   see: (OPTIONAL)
#     title: The Title of the Article (REQUIRED)
#     link: /web/fundamentals/woot (REQUIRED)
#   blink_component: Blink>GetUserMedia>WebCam (OPTIONAL - not used yet)
#   tags: (OPTIONAL - not used yet)
#   - tagA (REQUIRED - must validate from commonTags.json)
#   links: (OPTIONAL)
#   - title: Your First PWA Code Lab (REQUIRED)
#     link: /web/fundamentals/something (REQUIRED)
```

**Comment by Blind4Basics** [comment]
From what I've look at in the meantime, it seems we actually have to choose ourselves what data structures we'll use. Hence, first things first: with what data do we build this?

I'd suggest somehting like this:

```
name: ...
def:
notes: [ ] 
```

* `name`: mandatory
* `def`: short for "definition". Mandatory
* `notes`: optionnal. Would old a list of sentences that would automatically be written in smaller/gray/italic/whatever under the definition when present.


=> Something else?

**Comment by kazk** [comment]
The one you found looks good to me. But instead of allowing HTML, I'll allow Markdown in `description` and consider that required field.

**Comment by kazk** [comment]
I'll make something based on that and add a file with comment explaining the fields.
