### ISSUE TITLE
Create docs for "community" area

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#98]
Suggestion from kazk:

> > Any idea where CoC and organizational stuff would fit in current docs and in repo?
>
> Maybe under `/community`.
> - `/community` overview
> - `/community/teams/` organizational stuff. List of admins, mods, explain crown/shield, etc.
> - `/community/rules/` list of things that's not allowed within the Codewars community. The current CoC might need rewrite, I read somewhere that it's better to list things you're not allowed to do explicitly rather than listing how you should behave because the latter can be subjective.

I do not have a good idea how to reorganize CoC, so maybe, for the start, I will just import existing one. I will think about it.

Another question would be navigation: how to get there from the landing page? Use some other `kind` of doc? Or make it a `concept` of community?

Ideas are welcome!

**Comment by Blind4Basics** [comment]
I'd actually suggest the getting-started section, for this... :o

**Comment by hobovsky** [comment]
Is it possible to use crown/shield mark in Markdown, or any other way to put it in docs? I used emoji as an example for now, but maybe it could be replaced by something better?

**Comment by kazk** [comment]
SVGs I'm using are the following:

- https://github.com/tabler/tabler-icons/blob/master/icons/crown.svg
- https://github.com/tabler/tabler-icons/blob/master/icons/shield.svg

But I'm not sure if you can show them inline within the parentheses.

**Comment by kazk** [comment]
> Another question would be navigation: how to get there from the landing page? Use some other kind of doc? Or make it a concept of community?

Yeah, it's not really a documentation so it's difficult to categorize. We don't need to worry too much about it for now. We can always change.

---

The members of the Qualified team have `admin` role:

- alchemy (Nathan, CEO)
- jhoffner (Jake, CTO)
- OverZealous (Phil, Senior Frontend Developer)
- kazk (Kaz, Senior Software Developer)
- ggorlen (Greg, Content Lead)

But as you guys know already, I've been the only active admin and developer. For now, I think it's fine to just have my name for admins section.
Maybe there should be a section explaining things like the relationship between Qualified and Codewars, and list the Qualified team there.

---

My view on governance:

> Codewars grew organically without leadership and I don't think we (Qualified/Codewars) should start enforcing some rules we come up with after so many years of neglect. That's why I'm working with you guys to come up with better ways to manage Codewars and think of ways to improve. **I'd like the community team to lead the community autonomously** (most of the time). **I'll provide the tools/guidance and make final decisions whenever necessary**. **Codewars will continue to be community oriented, but with more structure.** I think that's the best way to evolve.

I'll expand the capability of the moderators whenever it makes sense and as I implement the required features.
Also, what we document here is official, even if it was mostly written by the community team.

**Comment by hobovsky** [comment]
@kazk @codewars/community Any idea what could be present on the overview page of the "community" section? I have completely no idea what to put here: https://deploy-preview-163--reverent-edison-2864ea.netlify.app/community/

**Comment by kazk** [comment]
Something like:

- Explain that Codewars is a platform driven by a global community
- Explain why it's important to keep the community healthy
- Briefly explain what we're doing to achieve that (this leads to moderation/rules)

We can do this later too, if you want. We should prioritize collecting documentations than improving the experience of the readers at the moment. I think it's nice to have an overview page that summarizes the topic, but we can wait.

---

Actually, it might be better to wait to avoid wasted efforts. I'm starting to think it's better to restructure under `moderating` to match other top-level topics.

- `moderating/` Overview
- `moderating/roles/` About admins/mods
- `moderating/self/` What normal users can do to help
- `moderating/rules/` Community rules

Don't worry about this yet. I'm still thinking about it.

---

(I'm not sure about `-ing` topics to be honest. But I want something consistent.)

**Comment by hobovsky** [comment]
OK I can leave it for now and wait until the idea gets better shape, no problem. What should I do with what's there currently? Merge it as it is now? Or without the blank "overview" page? Leave unmerged and move to something else?

**Comment by kazk** [comment]
You can merge it.

**Comment by hobovsky** [comment]
Merging, then. Reopen or create a new issue when you get some better idea and want to have it redone.
