### ISSUE TITLE
Import "Honor & Ranks"

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#99]
Move "Honor & Ranks" page from old wiki to new docs (breakdown of #5).

I will think how to organize stuff there to make it clearer and more exhaustive, but if anyone has any ideas or suggestions for this section, Please post them here.

**Comment by kazk** [comment]
I've split them into two.

- [Honor](https://github.com/codewars/docs/blob/master/__tmp__/wiki/honor.md)
- [Ranks](https://github.com/codewars/docs/blob/master/__tmp__/wiki/ranks.md)

For location, I guess

- `content/references/honor.md`
- `content/references/ranks.md`

We can move them later if we find a better place.

**Comment by hobovsky** [comment]
Merged into master by #112
